# Generated by Django 3.2.23 on 2024-01-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time_loggged',
            new_name='time_logged',
        ),
    ]
