# Generated by Django 3.2.23 on 2024-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0004_alter_session_wind_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='wind_conditions',
            field=models.CharField(choices=[('very light', 'very light'), ('light', 'light'), ('moderate', 'moderate'), ('strong', 'strong'), ('very strong', 'very strong'), ('dangerous', 'dangerous')], default='light', max_length=15),
        ),
    ]
