# Generated by Django 3.2.23 on 2024-01-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0005_alter_session_wind_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
    ]
