# Generated by Django 3.2.23 on 2024-01-18 17:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0007_alter_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
