# Generated by Django 3.2.23 on 2024-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0016_alter_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
