# Generated by Django 5.0.1 on 2024-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0017_alter_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
