# Generated by Django 5.0.1 on 2024-01-31 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0021_alter_session_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('author', 'date')},
        ),
    ]
